server:

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: demo
    password: demo123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

currencylayer:
  api:
    key: e91746a8a999f8635cd24ff933ea952e
    url: http://api.currencylayer.com/live

fixer:
  api:
    key: e2c72d40bfc9bd6f58431ec024dd184b
    url: http://data.fixer.io/api/latest

exchange:
  provider: currencylayer