spring:
  cache:
    type: redis

  redis:
    host: redis
    port: 6379

  datasource:
    url: jdbc:postgresql://demo-db:5432/demo_db
    username: demo
    password: demo123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080